import React from "react";
import type { Metadata } from "next";
import Footer from "@/components/common/Footer/Footer";
import QueryProvider from "@/providers/QueryProvider";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import { notFound } from "next/navigation";
import { routing } from "@/i18n/routing";
import Toastify from "@/components/common/toastify/Toastify";
import Navbar from "@/components/common/Navbar/Navbar";
import "@/styles/main.scss";

export const metadata: Metadata = {
  title: "Full E-Commerce",
  description: "Generated by create next app",
};

export const dynamicParams = true;

export async function generateStaticParams() {
  return routing.locales.map((locale) => ({ locale }));
}

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;

  if (!routing.locales.includes(locale as "en" | "ar")) {
    return notFound();
  }

  const messages = await getMessages({ locale });

  return (
    <html lang={locale} dir={locale === "ar" ? "rtl" : "ltr"}>
      <body>
        <QueryProvider>
          <NextIntlClientProvider messages={messages}>
            <Navbar />
            <ReactQueryDevtools initialIsOpen={false} />
            <main className="min-h-screen bg-gray-100 ">
              {children}
            </main>
            <Toastify />
            <Footer />
          </NextIntlClientProvider>
        </QueryProvider>
      </body>
    </html>
  );
}

